export const PERSONAL_DETAILS = 'PERSONAL_DETAILS';
export const EDUCATIONAL_DETAILS = 'EDUCATIONAL_DETAILS';
export const CONTACT_DETAILS = 'CONTACT_DETAILS';
export const REGISTER_DETAILS = 'REGISTER_DETAILS';
export const EDUCATION_FORM = 'EDUCATION_FORM';
export const PERSONAL_FORM = 'PERSONAL_FORM';
export const CONTACT_FORM = 'CONTACT_FORM';
export const REGISTER_FORM = 'REGISTER_FORM';
